<a href="https://colab.research.google.com/github/SweetlinN/Customer-Purchase-Prediction/blob/main/Customer_purchase_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# problem statement: Customer Purchase Prediction

# 1.import libraries

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split


from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder,StandardScaler
from sklearn.metrics import accuracy_score,precision_score,roc_auc_score,recall_score,f1_score,confusion_matrix,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

# 2. Data Gathering

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving decision_tree_dataset.csv to decision_tree_dataset.csv

In [ ]:
df = pd.read_csv("decision_tree_dataset.csv")

In [ ]:
# first five rows of the dataset

In [ ]:
df.head(5)

,Customer_Age,Income,Marital_Status,Education_Level,Number_of_Children,Shopping_History_Score,Product_Category_Interest,Discount_Offered,Purchased
0,57,74292,Married,PhD,0,56,Sports,26,Yes
1,68,23851,Married,PhD,3,93,Sports,40,No
2,47,71396,Single,PhD,1,95,Electronics,32,Yes
3,45,77218,Single,Bachelor,3,80,Fashion,38,Yes
4,33,23443,Single,PhD,5,83,Home Decor,8,No

In [ ]:
# last five rows of the dataset

In [ ]:
df.tail()

,Customer_Age,Income,Marital_Status,Education_Level,Number_of_Children,Shopping_History_Score,Product_Category_Interest,Discount_Offered,Purchased
995,35,48707,Single,PhD,3,60,Fashion,28,No
996,20,29063,Divorced,PhD,0,36,Home Decor,42,Yes
997,58,77691,Married,Master,3,37,Sports,40,No
998,69,27282,Divorced,Master,2,79,Electronics,49,No
999,69,81457,Single,Bachelor,4,14,Electronics,29,No

# 3.EDA(Exploratory Data Analysis)

In [ ]:
df.shape

(1000, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer_Age               1000 non-null   int64
 1   Income                     1000 non-null   int64
 2   Marital_Status             1000 non-null   object
 3   Education_Level            1000 non-null   object
 4   Number_of_Children         1000 non-null   int64
 5   Shopping_History_Score     1000 non-null   int64
 6   Product_Category_Interest  1000 non-null   object
 7   Discount_Offered           1000 non-null   int64
 8   Purchased                  1000 non-null   object
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

In [ ]:
df.isnull().sum()

Customer_Age                 0
Income                       0
Marital_Status               0
Education_Level              0
Number_of_Children           0
Shopping_History_Score       0
Product_Category_Interest    0
Discount_Offered             0
Purchased                    0
dtype: int64

In [ ]:
df.columns

Index(['Customer_Age', 'Income', 'Marital_Status', 'Education_Level',
       'Number_of_Children', 'Shopping_History_Score',
       'Product_Category_Interest', 'Discount_Offered', 'Purchased'],
      dtype='object')

# 4.feature creation

categorical colums to convert numerical values

In [ ]:
df['Education_Level'].value_counts()

Education_Level
Bachelor       267
PhD            250
Master         244
High School    239
Name: count, dtype: int64

In [ ]:
encoder = OrdinalEncoder()
df['Education_Level'] = encoder.fit_transform(df[['Education_Level']])

In [ ]:
df

,Customer_Age,Income,Marital_Status,Education_Level,Number_of_Children,Shopping_History_Score,Product_Category_Interest,Discount_Offered,Purchased
0,57,74292,Married,3.0,0,56,Sports,26,Yes
1,68,23851,Married,3.0,3,93,Sports,40,No
2,47,71396,Single,3.0,1,95,Electronics,32,Yes
3,45,77218,Single,0.0,3,80,Fashion,38,Yes
4,33,23443,Single,3.0,5,83,Home Decor,8,No
...,...,...,...,...,...,...,...,...,...
995,35,48707,Single,3.0,3,60,Fashion,28,No
996,20,29063,Divorced,3.0,0,36,Home Decor,42,Yes
997,58,77691,Married,2.0,3,37,Sports,40,No
998,69,27282,Divorced,2.0,2,79,Electronics,49,No
999,69,81457,Single,0.0,4,14,Electronics,29,No

In [ ]:
df['Marital_Status'].value_counts()

Marital_Status
Divorced    338
Single      337
Married     325
Name: count, dtype: int64

In [ ]:
encoder = LabelEncoder()
df['Marital_Status'] = encoder.fit_transform(df['Marital_Status'])

In [ ]:
df

,Customer_Age,Income,Marital_Status,Education_Level,Number_of_Children,Shopping_History_Score,Product_Category_Interest,Discount_Offered,Purchased
0,57,74292,1,3.0,0,56,Sports,26,Yes
1,68,23851,1,3.0,3,93,Sports,40,No
2,47,71396,2,3.0,1,95,Electronics,32,Yes
3,45,77218,2,0.0,3,80,Fashion,38,Yes
4,33,23443,2,3.0,5,83,Home Decor,8,No
...,...,...,...,...,...,...,...,...,...
995,35,48707,2,3.0,3,60,Fashion,28,No
996,20,29063,0,3.0,0,36,Home Decor,42,Yes
997,58,77691,1,2.0,3,37,Sports,40,No
998,69,27282,0,2.0,2,79,Electronics,49,No
999,69,81457,2,0.0,4,14,Electronics,29,No

In [ ]:
df['Purchased'].value_counts()

Purchased
No     680
Yes    320
Name: count, dtype: int64

In [ ]:
encoder = LabelEncoder()
df['Purchased'] = encoder.fit_transform(df['Purchased'])

In [ ]:
df

,Customer_Age,Income,Marital_Status,Education_Level,Number_of_Children,Shopping_History_Score,Product_Category_Interest,Discount_Offered,Purchased
0,57,74292,1,3.0,0,56,Sports,26,1
1,68,23851,1,3.0,3,93,Sports,40,0
2,47,71396,2,3.0,1,95,Electronics,32,1
3,45,77218,2,0.0,3,80,Fashion,38,1
4,33,23443,2,3.0,5,83,Home Decor,8,0
...,...,...,...,...,...,...,...,...,...
995,35,48707,2,3.0,3,60,Fashion,28,0
996,20,29063,0,3.0,0,36,Home Decor,42,1
997,58,77691,1,2.0,3,37,Sports,40,0
998,69,27282,0,2.0,2,79,Electronics,49,0
999,69,81457,2,0.0,4,14,Electronics,29,0

In [ ]:
# use onehotencoding

In [ ]:
 #Product_Category_Interest
df['Product_Category_Interest'].value_counts()

Product_Category_Interest
Electronics    265
Home Decor     260
Sports         248
Fashion        227
Name: count, dtype: int64

In [ ]:
data1 = df[['Product_Category_Interest']]

In [ ]:
data1

    Product_Category_Interest
0                      Sports
1                      Sports
2                 Electronics
3                     Fashion
4                  Home Decor
..                        ...
995                   Fashion
996                Home Decor
997                    Sports
998               Electronics
999               Electronics

[1000 rows x 1 columns]

In [ ]:
data2=pd.get_dummies(data1['Product_Category_Interest'],dtype=int)

In [ ]:
data2

     Electronics  Fashion  Home Decor  Sports
0              0        0           0       1
1              0        0           0       1
2              1        0           0       0
3              0        1           0       0
4              0        0           1       0
..           ...      ...         ...     ...
995            0        1           0       0
996            0        0           1       0
997            0        0           0       1
998            1        0           0       0
999            1        0           0       0

[1000 rows x 4 columns]

In [ ]:
# concat (serpathu)

new_data = pd.concat([df,data2],axis=1)

In [ ]:
new_data

,Customer_Age,Income,Marital_Status,Education_Level,Number_of_Children,Shopping_History_Score,Product_Category_Interest,Discount_Offered,Purchased,Electronics,Fashion,Home Decor,Sports
0,57,74292,1,3.0,0,56,Sports,26,1,0,0,0,1
1,68,23851,1,3.0,3,93,Sports,40,0,0,0,0,1
2,47,71396,2,3.0,1,95,Electronics,32,1,1,0,0,0
3,45,77218,2,0.0,3,80,Fashion,38,1,0,1,0,0
4,33,23443,2,3.0,5,83,Home Decor,8,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,35,48707,2,3.0,3,60,Fashion,28,0,0,1,0,0
996,20,29063,0,3.0,0,36,Home Decor,42,1,0,0,1,0
997,58,77691,1,2.0,3,37,Sports,40,0,0,0,0,1
998,69,27282,0,2.0,2,79,Electronics,49,0,1,0,0,0
999,69,81457,2,0.0,4,14,Electronics,29,0,1,0,0,0

In [ ]:
new_data.drop('Product_Category_Interest',axis=1,inplace=True)

In [ ]:
new_data.shape

(1000, 12)

In [ ]:
new_data

,Customer_Age,Income,Marital_Status,Education_Level,Number_of_Children,Shopping_History_Score,Discount_Offered,Purchased,Electronics,Fashion,Home Decor,Sports
0,57,74292,1,3.0,0,56,26,1,0,0,0,1
1,68,23851,1,3.0,3,93,40,0,0,0,0,1
2,47,71396,2,3.0,1,95,32,1,1,0,0,0
3,45,77218,2,0.0,3,80,38,1,0,1,0,0
4,33,23443,2,3.0,5,83,8,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,35,48707,2,3.0,3,60,28,0,0,1,0,0
996,20,29063,0,3.0,0,36,42,1,0,0,1,0
997,58,77691,1,2.0,3,37,40,0,0,0,0,1
998,69,27282,0,2.0,2,79,49,0,1,0,0,0
999,69,81457,2,0.0,4,14,29,0,1,0,0,0

# 5.Split the training data and testing data

In [ ]:
X=new_data.drop(["Purchased"],axis=1)
y=new_data["Purchased"]

In [ ]:
X

,Customer_Age,Income,Marital_Status,Education_Level,Number_of_Children,Shopping_History_Score,Discount_Offered,Electronics,Fashion,Home Decor,Sports
0,57,74292,1,3.0,0,56,26,0,0,0,1
1,68,23851,1,3.0,3,93,40,0,0,0,1
2,47,71396,2,3.0,1,95,32,1,0,0,0
3,45,77218,2,0.0,3,80,38,0,1,0,0
4,33,23443,2,3.0,5,83,8,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
995,35,48707,2,3.0,3,60,28,0,1,0,0
996,20,29063,0,3.0,0,36,42,0,0,1,0
997,58,77691,1,2.0,3,37,40,0,0,0,1
998,69,27282,0,2.0,2,79,49,1,0,0,0
999,69,81457,2,0.0,4,14,29,1,0,0,0

In [ ]:
y

0      1
1      0
2      1
3      1
4      0
      ..
995    0
996    1
997    0
998    0
999    0
Name: Purchased, Length: 1000, dtype: int64

In [ ]:
# normalise data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

# 6.Model Training and prediction and Evaluate

In [ ]:
# Logistic Regression

In [ ]:
lg = LogisticRegression()
lg.fit(X_train,y_train)

LogisticRegression()

In [ ]:
# Predictions
y_pred1 = lg.predict(X_test)

# Metrics
accuracy = accuracy_score(y_test, y_pred1)* 100
precision = precision_score(y_test, y_pred1)
recall = recall_score(y_test, y_pred1)
f1 = f1_score(y_test, y_pred1)


# Output
print("Accuracy of Logistic Regression:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy of Logistic Regression: 80.5
Precision: 0.6875
Recall: 0.6984126984126984
F1 Score: 0.6929133858267716

In [ ]:
# Random ForestClassifier

In [ ]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
# Predictions
y_pred2 = rf.predict(X_test)

# Metrics
accuracy = accuracy_score(y_test, y_pred2) * 100
precision = precision_score(y_test, y_pred2)
recall = recall_score(y_test, y_pred2)
f1 = f1_score(y_test, y_pred2)


# Output
print("Accuracy Random Forest Classifier:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy Random Forest Classifier: 100.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0

In [ ]:
# Support Vector Machine

In [ ]:
from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train, y_train)

SVC()

In [ ]:
# Predictions
y_pred3 = svm.predict(X_test)

# Metrics
accuracy = accuracy_score(y_test,y_pred3)*100
precision = precision_score(y_test, y_pred3)
recall = recall_score(y_test, y_pred3)
f1 = f1_score(y_test, y_pred3)

# Print results
print("Accuracy of SVM:",accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy of SVM: 68.5
Precision: 0.0
Recall: 0.0
F1 Score: 0.0

# 7.Improve the best model for hypertuning

In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define pipeline
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC(class_weight='balanced', probability=True))
])

# Define parameter grid
param_grid = {
    'svm__kernel': ['rbf', 'linear'],
    'svm__C': [0.1, 1, 10, 100],
    'svm__gamma': [1, 0.1, 0.01, 0.001]
}

# Grid search with pipeline
grid = GridSearchCV(pipeline, param_grid, cv=5)
grid.fit(X_train, y_train)

# Best pipeline model
best_pipeline = grid.best_estimator_

# Predictions
y_pred = best_pipeline.predict(X_test)

# Evaluation metrics
metrics = {
    "Precision": precision_score(y_test, y_pred),
    "Recall": recall_score(y_test, y_pred),
    "F1-score": f1_score(y_test, y_pred),
    "Accuracy": accuracy_score(y_test, y_pred)*100
}

print(metrics)

{'Precision': 0.8382352941176471, 'Recall': 0.9047619047619048, 'F1-score': 0.8702290076335878, 'Accuracy': 91.5}